services:
  cronicle:
    image: bluet/cronicle-docker:latest
    container_name: cronicle
    hostname: cronicle
    # environment:
      # - TZ=Asia/Taipei
      # - CRONICLE_base_app_url=http://cronicle/
    ports:
      - "3012:3012"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /data/docker/cronicle/data:/opt/cronicle/data
    - /data/docker/cronicle/logs:/opt/cronicle/logs
    - /data/docker/cronicle/plugins:/opt/cronicle/plugins
    - /data/docker/cronicle/workloads/app:/app
    restart: unless-stopped