import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar, SideBar } from "@/app/_components/home";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <main className="flex">
          <SideBar />
          <div className="flex-1">
            <NavBar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
