import { Theme } from "@/types/theme";
import type { Metadata } from "next";
import { CookiesProvider } from "next-client-cookies/server";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { cookies } from "next/headers";
import React from "react";
import "./globals.css";
import NavBar from "@/app/_components/home/NavBar/NavBar";
import RadixDirectionProvider from "@/app/_components/shared/RadixDirectionProvider";
import { getLangDir } from "rtl-detect";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>;

export default async function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const theme = cookies().get("theme")?.value as Theme;

  const messages = await getMessages();

  const dir = getLangDir(locale);

  return (
    <html dir={dir} lang={locale} className={theme ?? ""}>
      <body className="bg-background-darker text-foreground">
        <RadixDirectionProvider dir={dir}>
          <NextIntlClientProvider messages={messages}>
            <CookiesProvider>
              <NavBar />
            </CookiesProvider>
          </NextIntlClientProvider>
        </RadixDirectionProvider>
      </body>
    </html>
  );
}
