import RadixDirectionProvider from "@/components/wrappers/RadixDirectionProvider";
import getTheme from "@/utils/getTheme";
import type { Metadata } from "next";
import { CookiesProvider } from "next-client-cookies/server";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import React from "react";
import { getLangDir } from "rtl-detect";
import NavBar from "../../components/navbar/NavBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>;

export default async function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  const theme = getTheme();

  const messages = await getMessages();

  const dir = getLangDir(locale);

  return (
    <html dir={dir} lang={locale} className={theme ?? ""}>
      <body className="grid grid-rows-[auto,1fr] bg-background-darker text-foreground">
        <RadixDirectionProvider dir={dir}>
          <NextIntlClientProvider messages={messages}>
            <CookiesProvider>
              <NavBar />
              <div className="h-[calc(100vh-72px)] overflow-auto scrollbar-thin scrollbar-thumb-primary scrollbar-thumb-rounded-md">
                <main className="container mx-auto px-4 py-10 lg:px-10">
                  {children}
                </main>
              </div>
            </CookiesProvider>
          </NextIntlClientProvider>
        </RadixDirectionProvider>
      </body>
    </html>
  );
}
